server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
    # MySQL 数据库配置
  #    username: root
  #    password: root123456
  #    url: jdbc:mysql://127.0.0.1:3306/shortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      connection-test-query: select 1
  #      connection-timeout: 20000
  #      idle-timeout: 300000
  #      maximum-pool-size: 5
  #      minimum-idle: 5
  data:
    redis:
      host: 10.96.65.75
      port: 6379
      password: tiktokRedis
    channel-topic:
      short-link-stats: 'short_link:stats-stream'
      short-link-stats-group: 'short_link:stats-stream:only-group'

  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  stats:
    locale:
      amap-key: c9051fbec96d9693cfde943b7247b93a
  goto-domain:
    white-list:
      enable: true
      names: '抖音,知乎,掘金,博客园'
      details:
        - douyin.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
